version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        env_file:
            - .env.docker
        networks:
            - laravel
        command: >
            sh -c "php artisan key:generate && php-fpm" &&
            chmod -R 775 storage bootstrap/cache &&
            chown -R www-data:www-data storage bootstrap/cache

    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: postgres:15-alpine
        container_name: laravel_db
        restart: unless-stopped
        ports:
            - 5433:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
        env_file:
            - .env.docker
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        networks:
            - laravel

networks:
    laravel:

volumes:
    pgdata:
